services:
  backend:
    build: ./backend
    container_name: car_price_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - car-net

  frontend:
    build: ./frontend
    container_name: car_price_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - car-net

networks:
  car-net:
    driver: bridge
